# Generated by Django 5.1 on 2024-10-05 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_order_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Paid & Processing'), ('shipped', 'Shipped'), ('fulfilled', 'Fulfilled'), ('returned', 'Returned & Refunded')], default='pending', max_length=20),
        ),
    ]
