# Generated by Django 5.1 on 2024-10-08 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_wine_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wine',
            name='ph',
        ),
    ]
